#!/bin/bash

hostname

vars="MY_ENV_NAME MY_SPACK_COMMIT MY_SPACK_BRANCH MY_SPACK_REPO MY_SPACK_PARENT_DIR"

echo "--------------------------------"
echo "---- Variables of interest "
echo "--------------------------------"

for var in ${vars};
do
  echo "---- ${var} = ${!var} "
done

echo "--------------------------------"
