##############################################################################
# Copyright (c) 2019-2021, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

variables:
  #MY_SPACK_REPO: https://lc.llnl.gov/gitlab/radiuss/spack-mirror.git
  MY_SPACK_REPO: https://github.com/spack/spack.git
  #MY_SPACK_COMMIT: 2d464f8c8903ce57cabe411bbe979583d4ccdb5d # develop-2024-06-16
  #MY_SPACK_COMMIT: aeaa922eef45b14199b486fa2c188252df8c9544 # develop-2024-07-07
  #MY_SPACK_COMMIT: 38643e5a797b708192d2463fde05caf5ccb66ccd # Test PR https://github.com/spack/spack/pull/45648
  #MY_SPACK_COMMIT: d7f5dbaf8911387d6c38035f0d508702ee71b03a # Merge commit of radiuss packages update
  #MY_SPACK_COMMIT: 7ad08213dc343c50f3cea2d3627e92d4e54a6421 # develop-2024-10-06
  #MY_SPACK_COMMIT: 70534ac9d457da9bc884feb10a64974ad32c19e3 # develop-2025-01-12
  #MY_SPACK_COMMIT: c0bdc372266c53a078f32f910abe25c05848a74c # develop-2025-02-09
  #MY_SPACK_COMMIT: 280017a9ba3f6a969743deca0eebc96e7c0e5cfd # rsc-2025-03-0
  MY_SPACK_BRANCH: v1.0.2

include:
  - local: .gitlab/corona.yml
  - local: .gitlab/dane.yml
  - local: .gitlab/matrix.yml
  - local: .gitlab/tioga.yml
  - local: .gitlab/tuolumne.yml
