##############################################################################
# Copyright (c) 2019-2021, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

variables:
  MY_SPACK_REPO: https://github.com/spack/spack.git
  #MY_SPACK_COMMIT: 2d464f8c8903ce57cabe411bbe979583d4ccdb5d # develop-2024-06-16
  #MY_SPACK_COMMIT: aeaa922eef45b14199b486fa2c188252df8c9544 # develop-2024-07-07
  #MY_SPACK_COMMIT: 38643e5a797b708192d2463fde05caf5ccb66ccd # Test PR https://github.com/spack/spack/pull/45648
  #MY_SPACK_COMMIT: d7f5dbaf8911387d6c38035f0d508702ee71b03a # Merge commit of radiuss packages update
  #MY_SPACK_COMMIT: 7ad08213dc343c50f3cea2d3627e92d4e54a6421 # develop-2024-10-06
  MY_SPACK_COMMIT: 70534ac9d457da9bc884feb10a64974ad32c19e3 # develop-2025-01-12

include:
  - local: .gitlab/corona.yml
  - local: .gitlab/ruby.yml
  - local: .gitlab/poodle.yml
  - local: .gitlab/lassen.yml
  - local: .gitlab/tioga.yml
