##############################################################################
# Copyright (c) 2019-2021, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

variables:
  #MY_SPACK_REPO: https://lc.llnl.gov/gitlab/radiuss/spack-mirror.git
  MY_SPACK_REPO: https://github.com/spack/spack.git
  MY_SPACK_BRANCH: v1.1.1

include:
  - local: .gitlab/corona.yml
  - local: .gitlab/dane.yml
  #- local: .gitlab/matrix.yml
  - local: .gitlab/tioga.yml
  - local: .gitlab/tuolumne.yml
